import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Fragment, useEffect, useState } from 'react';
import { useAccount, useConnect, useEnsName, useEnsAvatar, useDisconnect, useFeeData } from 'wagmi'
import { useConnectModal, useGasPrice } from '@/hooks/useConnect';
import Link from 'next/link';
import { Dialog, Menu, Transition, Tab } from '@headlessui/react';
import Modal from '@/components/Modal';
// import { Area } from '@antv/g2plot';

export default function Item() {
  const { isConnected } = useConnectModal();
  const [range, setRange] = useState(1);
  const [buyBondOpen, setBuyBondOpen] = useState(false);
  const [modalStep, setModalStep] = useState(1);

  useEffect(() => {
    const { Area } = window?.G2Plot;
    fetch('/api/chart')
    .then((res) => res.json())
    .then((data) => {
      const area = new Area('xxx', {
        data,
        xField: 'Date',
        yField: 'scales',
        xAxis: {
          range: [0, 1],
          tickCount: 5,
          line: {
            color: '#000000',
          },
          grid: null,
        },
        yAxis: {
          grid: {
            line: {
              lineWidth: 5,
              lineDash: [5, 2]
            }
          },
        },
        smooth: true,
        areaStyle: () => {
          return {
            fill: 'l(270) 0:#11102b 0.4:#504460 1:#ffffff',
            fillOpacity: 0.8,
          };
        },
        line: {
          color: '#ffffff'
        }
      });
      area.render();
    });
  }, []);

  const buyBond = () => {
    setModalStep(2);
    setTimeout(() => {
      setModalStep(3)
    }, 2000);
  }

  const openModal = () => {
    setBuyBondOpen(true);
  }

  const closeModal = () => {
    setBuyBondOpen(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-screen-xl m-auto pt-24 pb-17 flex flex-col'>
        <div className='mt-2 flex flex-row items-center'>
          <div className='w-80'>
            <Link href={'/'}>
              <div className='flex flex-row items-top text-xl font-bold'>
                <div className='w-8 h-8 mr-4 bg-indigo-900 rounded-full flex items-center justify-center'>
                  <img className='' src='/arrow-left.svg' />
                </div>
                <span className='mt-1'>Back to Bonds List</span>
              </div>
            </Link>
            <p className='mt-3 text-base'>First Bonds Market</p>
            <p className='mt-1 text-xs text-white/60 leading-5'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui nibh. Phasellus eleifend ipsum condimentum, malesuada nisl in, tincidunt mauris. </p>
          </div>
          <div className='flex-1 h-24 rounded-lg bg-debond/40 ml-36 px-3 py-2 grid grid-cols-3 pl-6 pt-5'>
            <div className={`flex flex-col`}>
              <div className='flex flex-row items-center'>
                <div className='rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold z-10' style={{
                  background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                }}>
                  {isConnected ? <img src='/checked.svg' /> : 1}
                </div>
                <div className='h-1 flex-1 bg-debondLine'></div>
              </div>
              <div className='text-base mt-2'>Connect Your Wallet</div>
            </div>
            <div className={`flex flex-col ${isConnected ? '' : 'opacity-30'}`}>
              <div className='flex flex-row items-center'>
                <div className='rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold z-10' style={{
                  background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                }}>
                  {isConnected ? <img src='/checked.svg' /> : 2}
                </div>
                <div className='h-1 flex-1 bg-debondLine'></div>
              </div>
              <div className='text-base mt-2'>Select Bond Type</div>
            </div>
            <div className={`flex flex-col ${isConnected ? '' : 'opacity-30'}`}>
              <div className='flex flex-row items-center'>
                <div className='rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold z-10' style={{
                  background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                }}>
                  3
                </div>
                <div className='h-1 flex-1 bg-debondLine'></div>
              </div>
              <div className='text-base mt-2'>Select Collateral</div>
            </div>
          </div>
        </div>
        <div className='mt-8 flex flex-col gap-4 flex-1'>
          <div className='flex flex-row gap-10 min-h-72 mb-4'>
            <div id='xxx' className='w-1/2 h-72'></div>
            <div className='flex flex-col gap-4 flex-1'>
              <div className='text-lg font-bold'>D/BOND fix rate (6m) DBGT Bond</div>
              <div className='flex flex-row items-center justify-between opacity-70'>
                <div className='flex flex-row items-center'>
                  <img src='/seen.svg' />
                  <div className='text-xs ml-1'>967 views</div>
                </div>
                <div className='flex flex-row items-center gap-2'>
                  <div className='flex flex-row items-center'>
                    <div className='text-xs mr-1'>set a reminder</div>
                    <img src='/reminder.svg' />
                  </div>
                  <div className='flex flex-row items-center'>
                    <div className='text-xs mr-1'>bookmark bond</div>
                    <img src='/bookmark.svg' />
                  </div>
                </div>
              </div>
              <div className='text-xs'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui nibh. Phasellus eleifend ipsum condimentum, malesuada nisl in, tincidunt mauris. Nullam eget aliquam erat. Integer luctus volutpat justo ac facilisis.
              </div>
              <div className='mt-auto'>
                <div className='w-full rounded-lg grid grid-cols-4 bg-debond/40 py-3 px-6'>
                  <div className='text-xs font-semibold text-center'>RATING:</div>
                  <div className='text-xs font-semibold text-center'>ASSETS:</div>
                  <div className='text-xs font-semibold text-center'>PERIOD:</div>
                  <div className='text-xs font-semibold text-center'>TYPE:</div>
                </div>
                <div className='w-full rounded-lg grid grid-cols-4 bg-debond py-3 px-6 mt-2'>
                  <div className='text-xs text-center'>AAA</div>
                  <div className='text-xs text-center'>DBGT</div>
                  <div className='text-xs text-center'>6M</div>
                  <div className='text-xs text-center'>FIXED RATE</div>
                </div>
              </div>
            </div>
          </div>
          <Tab.Group>
            <Tab.List className='flex flex-row items-center gap-4'>
              <Tab key={'buy'} className={({ selected }) => `w-60 h-10 flex items-center justify-center text-sm rounded-lg bg-debond focus:outline-none ${selected ? '' : 'opacity-50'}`}>Buy Bond</Tab>
              <Tab key={'stake'} className={({ selected }) => `w-60 h-10 flex items-center justify-center text-sm rounded-lg bg-debond focus:outline-none ${selected ? '' : 'opacity-50'}`}>Stake Bond</Tab>
              <Tab key={'detail'} className={({ selected }) => `w-60 h-10 flex items-center justify-center text-sm rounded-lg bg-debond focus:outline-none ${selected ? '' : 'opacity-50'}`}>Bond Detail</Tab>
            </Tab.List>
            <Tab.Panels>
              <Tab.Panel key={'buy'} className='flex flex-row gap-16 p-10 pt-8 bg-debond/40 rounded-lg h-80'>
                <div className='flex-1'>
                  <div className='h-5 flex flex-row items-center gap-6 mr-3'>
                    <Menu as={'div'} className="flex-1 relative inline-block">
                      <Menu.Button className='w-full flex flex-row items-center justify-center opacity-60'>
                        <div className='text-sm'>Collateral</div>
                        <img className='ml-2' src='/filter.svg' />
                      </Menu.Button>
                      <Transition
                        as={Fragment}
                        enter="transition ease-out duration-100"
                        enterFrom="transform opacity-0 scale-95"
                        enterTo="transform opacity-100 scale-100"
                        leave="transition ease-in duration-75"
                        leaveFrom="transform opacity-100 scale-100"
                        leaveTo="transform opacity-0 scale-95"
                      >
                        <Menu.Items className="absolute -left-4 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-highlight-2 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" style={{
                          background: 'linear-gradient(180deg, #211F71 0%, #090824 100%)',
                        }}>
                          <div className="px-2 py-2">
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  All
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  N/A
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  D/Bond
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  A55
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  Equisafe
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                          </div>
                        </Menu.Items>
                      </Transition>
                    </Menu>
                    <div className='flex-1 flex flex-row items-center justify-center'>
                      <div className='text-sm'>Maturity</div>
                      <img className='ml-2' src='/filter.svg' />
                    </div>
                    <div className='flex-1 flex flex-row items-center justify-center'>
                      <div className='text-sm'>Face Value</div>
                      <img className='ml-2' src='/filter.svg' />
                    </div>
                    <div className='w-16 flex flex-row items-center justify-center'>
                      <div className='text-sm'>APY</div>
                      <img className='ml-2' src='/filter.svg' />
                    </div>
                  </div>
                  <div className='flex flex-1 overflow-auto mt-2'>
                    <div className='flex flex-col gap-1 flex-1 h-48 mr-3'>
                      {[[{
                        key: '1',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      },{
                        key: '2',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      },{
                        key: '3',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      },{
                        key: '4',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      }]].map((page) => page.map(item => <Link key={item.key} href={`/bonds/${item.hash}`}>
                        <div className='flex flex-row items-center flex-none gap-4 rounded-lg bg-debond/40 hover:bg-highlight-2/40 text-sm h-12'>
                          <div className='flex-1 flex flex-row items-center justify-center'>
                            <img src='' />
                            <div className='ml-2'>{item.collateral}</div>
                          </div>
                          <div className='flex-1 text-center flex flex-row items-center justify-center'>{item.maturity}</div>
                          <div className='flex-1 text-center flex flex-row items-center justify-center'>{item.value}</div>
                          <div className='w-16 text-center flex flex-row items-center justify-center'>{item.apy}</div>
                        </div>
                      </Link>
                      ))}
                    </div>
                  </div>
                </div>
                <div className='flex-1 flex flex-col gap-4 text-xs'>
                  <div className='grid grid-cols-3 gap-4'>
                    <div>
                      <div className='opacity-60 font-semibold'>Maturity</div>
                      <div className='font-medium mt-2'>20-02-2022</div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Face Value</div>
                      <div className='font-medium mt-2'>e.g. $4545.45...</div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Intrest rate</div>
                      <div className='font-medium mt-2'>11.24% (APY 23.21%)</div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Amount USD:</div>
                      <div className='mt-2'>
                        <input className='w-full placeholder:text-white/60 bg-debond/40 border border-debond rounded-lg focus:outline-none focus:ring-0 px-4 py-3' placeholder='e.g. $4545.45...|' type={'text'} name={'amount'} />
                      </div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Percentage:</div>
                      <div className='mt-2'>
                        <input className='w-full placeholder:text-white/60 bg-debond/40 border border-debond rounded-lg focus:outline-none focus:ring-0 px-4 py-3' placeholder='e.g. $4545.45...|' type={'text'} name={'amount'} />
                      </div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Amount WETH:</div>
                      <div className='mt-2'>
                        <input className='w-full placeholder:text-white/60 bg-debond/40 border border-debond rounded-lg focus:outline-none focus:ring-0 px-4 py-3' placeholder='e.g. $4545.45...|' type={'text'} name={'amount'} />
                      </div>
                    </div>
                  </div>
                  <div className='flex flex-row items-center gap-8'>
                    <input
                      type="range"
                      defaultValue={range}
                      min="1"
                      max="100"
                      className="flex-1 h-1 bg-debondLine accent-white rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
                      onChange={(e) => {
                        setRange(e.target.value)
                      }}
                    />
                    <div className='text-white/60 text-xs'>{`(max: $54,211.22)`}</div>
                  </div>
                  <div className='flex flex-row-reverse items-center gap-6 mt-auto'>
                    <div className='px-16 py-3 text-sm rounded-lg cursor-pointer' style={{
                      background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                    }} onClick={openModal}>Buy Bond</div>
                    <div className='flex flex-row items-center text-sm'>
                      Save
                      <svg className='w-4 h-4 ml-2' viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fillRule="evenodd" clipRule="evenodd" d="M4.66642 1.37305H11.3331C12.4609 1.39855 13.3554 2.33183 13.3331 3.45971V13.2464C13.3359 13.7903 13.0205 14.2856 12.5264 14.513C12.3581 14.5863 12.1767 14.6248 11.9931 14.6264C11.6688 14.6244 11.3571 14.5007 11.1198 14.2797L7.99976 11.4397L4.87976 14.2797C4.49533 14.6227 3.94768 14.7136 3.47309 14.513C2.97906 14.2856 2.66363 13.7903 2.66642 13.2464V3.45971C2.64409 2.33183 3.53861 1.39855 4.66642 1.37305ZM8.88643 10.453L11.9998 13.293V3.45971C12.0189 3.06926 11.723 2.73487 11.3331 2.70638H4.66642C4.27654 2.73487 3.98062 3.06926 3.99976 3.45971V13.2464L7.08642 10.453C7.5959 9.98695 8.37695 9.98695 8.88643 10.453Z" fill="white"/>
                      </svg>
                    </div>
                    <div className='text-sm'>
                      Discard Input
                    </div>
                  </div>
                </div>
              </Tab.Panel>
              <Tab.Panel key={'stake'} className='flex flex-row gap-16 p-10 pt-8 bg-debond/40 rounded-lg h-80'>
                <div className='flex-1'>
                  <div className='h-5 flex flex-row items-center gap-6 mr-3'>
                    <Menu as={'div'} className="flex-1 relative inline-block">
                      <Menu.Button className='w-full flex flex-row items-center justify-center opacity-60'>
                        <div className='text-sm'>Collateral stake</div>
                        <img className='ml-2' src='/filter.svg' />
                      </Menu.Button>
                      <Transition
                        as={Fragment}
                        enter="transition ease-out duration-100"
                        enterFrom="transform opacity-0 scale-95"
                        enterTo="transform opacity-100 scale-100"
                        leave="transition ease-in duration-75"
                        leaveFrom="transform opacity-100 scale-100"
                        leaveTo="transform opacity-0 scale-95"
                      >
                        <Menu.Items className="absolute -left-4 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-highlight-2 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" style={{
                          background: 'linear-gradient(180deg, #211F71 0%, #090824 100%)',
                        }}>
                          <div className="px-2 py-2">
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  All
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  N/A
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  D/Bond
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  A55
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className={`${
                                    active ? 'text-white' : 'text-gray-500'
                                  } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                                >
                                  Equisafe
                                  <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                                    background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                                  }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                                </button>
                              )}
                            </Menu.Item>
                          </div>
                        </Menu.Items>
                      </Transition>
                    </Menu>
                    <div className='flex-1 flex flex-row items-center justify-center'>
                      <div className='text-sm'>Maturity</div>
                      <img className='ml-2' src='/filter.svg' />
                    </div>
                    <div className='flex-1 flex flex-row items-center justify-center'>
                      <div className='text-sm'>Face Value</div>
                      <img className='ml-2' src='/filter.svg' />
                    </div>
                    <div className='w-16 flex flex-row items-center justify-center'>
                      <div className='text-sm'>APY</div>
                      <img className='ml-2' src='/filter.svg' />
                    </div>
                  </div>
                  <div className='flex flex-1 overflow-auto mt-2'>
                    <div className='flex flex-col gap-1 flex-1 h-48 mr-3'>
                      {[[{
                        key: '1',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      },{
                        key: '2',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      },{
                        key: '3',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      },{
                        key: '4',
                        collateral: 'WETH',
                        maturity: '20-02-2022',
                        value: '$41,2121.21',
                        apy: '9%',
                      }]].map((page) => page.map(item => <Link key={item.key} href={`/bonds/${item.hash}`}>
                        <div className='flex flex-row items-center flex-none gap-4 rounded-lg bg-debond/40 hover:bg-highlight-2/40 text-sm h-12'>
                          <div className='flex-1 flex flex-row items-center justify-center'>
                            <img src='' />
                            <div className='ml-2'>{item.collateral}</div>
                          </div>
                          <div className='flex-1 text-center flex flex-row items-center justify-center'>{item.maturity}</div>
                          <div className='flex-1 text-center flex flex-row items-center justify-center'>{item.value}</div>
                          <div className='w-16 text-center flex flex-row items-center justify-center'>{item.apy}</div>
                        </div>
                      </Link>
                      ))}
                    </div>
                  </div>
                </div>
                <div className='flex-1 flex flex-col gap-4 text-xs'>
                  <div className='grid grid-cols-3 gap-4'>
                    <div>
                      <div className='opacity-60 font-semibold'>Maturity</div>
                      <div className='font-medium mt-2'>20-02-2022</div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Face Value</div>
                      <div className='font-medium mt-2'>e.g. $4545.45...</div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Intrest rate</div>
                      <div className='font-medium mt-2'>11.24% (APY 23.21%)</div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Amount USD:</div>
                      <div className='mt-2'>
                        <input className='w-full placeholder:text-white/60 bg-debond/40 border border-debond rounded-lg focus:outline-none focus:ring-0 px-4 py-3' placeholder='e.g. $4545.45...|' type={'text'} name={'amount'} />
                      </div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Percentage:</div>
                      <div className='mt-2'>
                        <input className='w-full placeholder:text-white/60 bg-debond/40 border border-debond rounded-lg focus:outline-none focus:ring-0 px-4 py-3' placeholder='e.g. $4545.45...|' type={'text'} name={'amount'} />
                      </div>
                    </div>
                    <div>
                      <div className='opacity-60 font-semibold'>Amount WETH:</div>
                      <div className='mt-2'>
                        <input className='w-full placeholder:text-white/60 bg-debond/40 border border-debond rounded-lg focus:outline-none focus:ring-0 px-4 py-3' placeholder='e.g. $4545.45...|' type={'text'} name={'amount'} />
                      </div>
                    </div>
                  </div>
                  <div className='flex flex-row items-center gap-8'>
                    <input
                      type="range"
                      defaultValue={range}
                      min="1"
                      max="100"
                      className="flex-1 h-1 bg-debondLine accent-white rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
                      onChange={(e) => {
                        setRange(e.target.value)
                      }}
                    />
                    <div className='text-white/60 text-xs'>{`(max: $54,211.22)`}</div>
                  </div>
                  <div className='flex flex-row-reverse items-center gap-6 mt-auto'>
                    <div className='px-16 py-3 text-sm rounded-lg cursor-pointer' style={{
                      background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                    }} onClick={openModal}>Buy Bond</div>
                    <div className='flex flex-row items-center text-sm'>
                      Save
                      <svg className='w-4 h-4 ml-2' viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fillRule="evenodd" clipRule="evenodd" d="M4.66642 1.37305H11.3331C12.4609 1.39855 13.3554 2.33183 13.3331 3.45971V13.2464C13.3359 13.7903 13.0205 14.2856 12.5264 14.513C12.3581 14.5863 12.1767 14.6248 11.9931 14.6264C11.6688 14.6244 11.3571 14.5007 11.1198 14.2797L7.99976 11.4397L4.87976 14.2797C4.49533 14.6227 3.94768 14.7136 3.47309 14.513C2.97906 14.2856 2.66363 13.7903 2.66642 13.2464V3.45971C2.64409 2.33183 3.53861 1.39855 4.66642 1.37305ZM8.88643 10.453L11.9998 13.293V3.45971C12.0189 3.06926 11.723 2.73487 11.3331 2.70638H4.66642C4.27654 2.73487 3.98062 3.06926 3.99976 3.45971V13.2464L7.08642 10.453C7.5959 9.98695 8.37695 9.98695 8.88643 10.453Z" fill="white"/>
                      </svg>
                    </div>
                    <div className='text-sm'>
                      Discard Input
                    </div>
                  </div>
                </div>
              </Tab.Panel>
              <Tab.Panel key={'detail'} className='flex flex-col items-center p-4 bg-debond/40 rounded-lg h-80'>
                <Tab.Group as={Fragment}>
                  <Tab.List className='flex flex-row items-start self-end gap-6'>
                    <Tab key={'pitch'} className={({ selected }) => `${selected ? 'border-b-2 border-debondLine' : 'text-white/40'} focus:outline-none`}>Pitch</Tab>
                    <Tab key={'update'} className={({ selected }) => `${selected ? 'border-b-2 border-debondLine' : 'text-white/40'} focus:outline-none`}>Update</Tab>
                    <Tab key={'review'} className={({ selected }) => `${selected ? 'border-b-2 border-debondLine' : 'text-white/40'} focus:outline-none`}>Review</Tab>
                  </Tab.List>
                  <Tab.Panels as={Fragment}>
                    <Tab.Panel key={'pitch'} className='flex flex-col items-center'>
                      <img className='h-36' src='/success.png' />
                      <div className='text-sm mt-4'>Check our documentation and Pitch Deck here</div>
                      <div className='px-16 py-3 text-sm rounded-lg cursor-pointer mt-4 mb-2' style={{
                        background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                      }} onClick={openModal}>Download Our Pitch Deck</div>
                    </Tab.Panel>
                    <Tab.Panel key={'update'} className='w-full flex flex-row items-center mt-5 gap-8'>
                      <div className='flex flex-1 h-56 overflow-auto'>
                        <div className='flex flex-col gap-1 flex-1 h-48 mr-3'>
                          {[[{
                            key: '1',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          },{
                            key: '2',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          },{
                            key: '3',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          },{
                            key: '4',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          },{
                            key: '4',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          },{
                            key: '4',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          },{
                            key: '4',
                            time: '15/12/2022 23:50',
                            content: '@cryptouser has placed a bid on this listing in the value of 500 DBIT',
                          }]].map((page) => page.map(item => <Link key={item.key} href={`/bonds/${item.hash}`}>
                            <div className='flex flex-row items-center flex-none gap-4 px-4 rounded-lg bg-debond/40 hover:bg-highlight-2/40 text-sm h-12'>
                              <div className='text-xs rounded-lg bg-debond py-0.5 px-2'>Yours</div>
                              <div className=''>{item.time}</div>
                              <div className='flex-1'>{item.content}</div>
                            </div>
                          </Link>
                          ))}
                        </div>
                      </div>
                      <div className='w-80 h-56 px-12 py-5 flex flex-col items-center bg-debond/40 rounded-lg'>
                        <img src='/wallet.png' />
                        <div className='mt-2'>Lorem ipsum dolore</div>
                        <div className='mt-1 text-white/40 text-xs text-center'>To be able to place your bonds on auction, you need to connect your wallet first!</div>
                      </div>
                    </Tab.Panel>
                    <Tab.Panel key={'review'} className='flex flex-col items-center'>
                    </Tab.Panel>
                  </Tab.Panels>
                </Tab.Group>
              </Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </div>
      <Modal show={buyBondOpen} onClose={closeModal}>
        {modalStep == 1 && <div className='flex flex-row gap-24 text-white font-Inter'>
          <div className='flex-1'>
            <div className='text-2xl font-semibold'>You’re about to buy a bond</div>
            <div className='mt-10'>
              <div className='flex flex-row items-center text-base'>
                About BondID
                <svg className='w-4 h-4 ml-2' viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M3 14C2.73333 14 2.5 13.9 2.3 13.7C2.1 13.5 2 13.2667 2 13V3C2 2.73333 2.1 2.5 2.3 2.3C2.5 2.1 2.73333 2 3 2H7.65V3H3V13H13V8.35H14V13C14 13.2667 13.9 13.5 13.7 13.7C13.5 13.9 13.2667 14 13 14H3ZM6.36667 10.35L5.66667 9.63333L12.3 3H8.65V2H14V7.35H13V3.71667L6.36667 10.35Z" fill="white"/>
                </svg>
              </div>
              <div className='text-white/40 text-base'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at vestibulum felis. Donec rhoncus turpis in ligula egestas posuere.</div>
            </div>
            <div className='mt-16 px-5 py-1 flex flex-row items-center text-xl bg-debond/40 rounded-lg border border-debond gap-2'>
              <div className='text-base'>Staking amount:</div>
              <input className='flex-1 bg-transparent border-none focus:outline-none focus:ring-0 text-right' type='text' name='amount' placeholder='343434.34' />
              <div className=' text-white/40 text-base'>{`(≈$4545.45)`}</div>
            </div>
            <div className='flex items-center justify-center mt-10 text-sm'>
              <div className='bg-highlight-2/40 rounded-lg text-center py-3 cursor-pointer px-16' onClick={buyBond}>Buy Bond</div>
            </div>
          </div>
        </div>}
        {modalStep == 2 && <div className='flex flex-col items-center'>
          <img className='animate-spin my-24' src='/loader.png' />
          <div className='text-base text-white'>hold still, we are processing your transaction!</div>
          <div className='text-base mt-1 text-white/60'>Don’t close the window just yet; we will finish up soon.</div>
        </div>}
        {modalStep == 3 && <div className='flex flex-col items-center text-white'>
          <div className='self-start text-2xl font-semibold'>Congratulations!</div>
          <img className='my-5' src='/success.png' />
          <div className='text-base text-white'>you have successfully bought BondID!</div>
          <div className='text-base mt-1 text-white/60'>You can find all your bonds in the Bond Wallet.</div>
          <div className='flex flex-row items-center justify-center text-sm mt-5'>
            <div className='bg-highlight-2/40 rounded-lg text-center py-3 cursor-pointer px-16' onClick={closeModal}>Go Back To Dashboard</div>
            <div className='xt-center py-3 cursor-pointer px-16' onClick={() => setModalStep(4)}>Go To Bond Wallet</div>
          </div>
        </div>}
        {modalStep == 4 && <div className='flex flex-col items-center text-white'>
          <div className='self-start text-2xl font-semibold'>Whoops! Something Went Wrong.</div>
          <img className='mt-8 mb-5' src='/error.png' />
          <div className='text-base text-white'>There Has Been An Issue</div>
          <div className='text-base mt-1 text-white/60'>For some reason, the transaction didn’t go through.</div>
          <div className='flex flex-row items-center justify-center text-sm mt-5'>
            <div className='bg-highlight-2/40 rounded-lg text-center py-3 cursor-pointer px-16' onClick={() => {
              closeModal();
              setTimeout(() => setModalStep(1), 1000);
            }}>Try Again</div>
            <div className='xt-center py-3 cursor-pointer px-16' onClick={closeModal}>Cancel</div>
          </div>
        </div>}
      </Modal>
    </>
  )
}
