import Head from 'next/head'
import Image from 'next/image'
import { Dialog, Transition, Menu } from '@headlessui/react';
import { Fragment, useEffect, useState } from 'react';
import Link from 'next/link';
import { useAccount, useConnect, useEnsName, useEnsAvatar, useDisconnect, useFeeData } from 'wagmi'
import { useConnectModal, useGasPrice } from '@/hooks/useConnect';
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query';
import { useQuery, useInfiniteQuery } from 'wagmi';

export default function Home() {
  const { isConnected } = useConnectModal();
  const { address } = useAccount();
  const [type, setType] = useState('all');

  const fetchClasses = async ({ pageParam = 0 }) => {
    return [1,2,3,4,5,6,7,7,7,7,7,7]
    const res = await fetch('/api/projects?cursor=' + pageParam)
    return res.json()
  }

  // const { data: metadatas } = useQuery('metadatas', () => {
  //   return [];
  // });

  const { data: profileMetadatas } = useQuery(['metadatas', {
    address,
    type,
  }], () => [], {

  });

  const {
    data: classes,
    error,
    fetchNextPage,
    hasNextPage,
    isFetching,
    isFetchingNextPage,
    status,
  } = useInfiniteQuery({
    queryKey: ['classes', {
      type,
      metadatas: profileMetadatas,
    }],
    queryFn: fetchClasses,
    getNextPageParam: (lastPage, pages) => pages.length + 1,
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-screen-xl m-auto pt-24 pb-17 flex flex-col h-full'>
        <div className='mt-2 flex flex-row items-center'>
          <div className='w-80'>
            <div className='flex flex-row items-top text-3xl font-bold'>
              <div className='py-2 mr-4'>
                <img className='w-8 h-8' src='/header/bond.svg' />
              </div>
              <span className='mt-1'>Bond Exchange</span>
            </div>
            <p className='mt-3 text-base'>Availavle Auctions</p>
            <p className='mt-1 text-xs text-white/60 leading-5'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui nibh. Phasellus eleifend ipsum condimentum, malesuada nisl in, tincidunt mauris. </p>
          </div>
          <div className='flex-1 h-24 rounded-lg bg-debond/40 ml-36 px-3 py-2 grid grid-cols-3 pl-6 pt-5'>
            <div className={`flex flex-col`}>
              <div className='flex flex-row items-center'>
                <div className='rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold z-10' style={{
                  background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                }}>
                  {isConnected ? <img src='/checked.svg' /> : 1}
                </div>
                <div className='h-1 flex-1 bg-debondLine'></div>
              </div>
              <div className='text-base mt-2'>Connect Your Wallet</div>
            </div>
            <div className={`flex flex-col ${isConnected ? '' : 'opacity-30'}`}>
              <div className='flex flex-row items-center'>
                <div className='rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold z-10' style={{
                  background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                }}>
                  2
                </div>
                <div className='h-1 flex-1 bg-debondLine'></div>
              </div>
              <div className='text-base mt-2'>Select Bond Type</div>
            </div>
            <div className='flex flex-col opacity-30'>
              <div className='flex flex-row items-center'>
                <div className='rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold z-10' style={{
                  background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                }}>
                  3
                </div>
                <div className='h-1 flex-1 bg-debondLine'></div>
              </div>
              <div className='text-base mt-2'>Select Collateral</div>
            </div>
          </div>
        </div>
        <div className='mt-8 flex flex-col gap-4 flex-1'>
          <div className='flex flex-row items-center gap-4'>
            <div className='w-60 h-10 flex items-center justify-center text-sm rounded-lg bg-debond'>Available Auctions</div>
            <div className='w-60 h-10 flex items-center justify-center text-sm rounded-lg bg-debond opacity-50'>Create New auction</div>
            <div className='w-60 h-10 flex items-center justify-center text-sm rounded-lg bg-debond opacity-50'>Your Auctions</div>
            <label className="flex-1 h-10 relative block">
              <span className="sr-only">Search</span>
              <span className="absolute inset-y-0 left-0 flex items-center pl-2">
                <svg className="h-4 w-4 mx-1 fill-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0 1 11 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 0 1-1.969 5.617zm-2.006-.742A6.977 6.977 0 0 0 18 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 0 0 4.875-1.975l.15-.15z"/></svg>
              </span>
              <input className="h-full bg-transparent placeholder:text-white block w-full border-2 border-debond rounded-lg py-2 pl-9 pr-3 shadow-sm focus:outline-none focus:border-debond focus:ring-debond focus:ring-0 sm:text-xs" placeholder="Search all bonds" type="text" name="search"/>
            </label>
          </div>
          <div className='h-8 flex flex-row items-center gap-4 rounded-lg bg-debond/40 px-12'>
            <Menu as={'div'} className="flex-1 relative inline-block text-left">
              <Menu.Button className=' flex flex-row items-center'>
                <div className='text-xs font-bold'>Issuer</div>
                <img className='ml-2' src='/filter.svg' />
              </Menu.Button>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-100"
                enterFrom="transform opacity-0 scale-95"
                enterTo="transform opacity-100 scale-100"
                leave="transition ease-in duration-75"
                leaveFrom="transform opacity-100 scale-100"
                leaveTo="transform opacity-0 scale-95"
              >
                <Menu.Items className="absolute -left-4 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-highlight-2 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" style={{
                  background: 'linear-gradient(180deg, #211F71 0%, #090824 100%)',
                }}>
                  <div className="px-2 py-2">
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          className={`${
                            active ? 'text-white' : 'text-gray-500'
                          } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                        >
                          All
                          <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                            background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                          }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                        </button>
                      )}
                    </Menu.Item>
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          className={`${
                            active ? 'text-white' : 'text-gray-500'
                          } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                        >
                          N/A
                          <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                            background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                          }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                        </button>
                      )}
                    </Menu.Item>
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          className={`${
                            active ? 'text-white' : 'text-gray-500'
                          } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                        >
                          D/Bond
                          <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                            background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                          }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                        </button>
                      )}
                    </Menu.Item>
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          className={`${
                            active ? 'text-white' : 'text-gray-500'
                          } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                        >
                          A55
                          <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                            background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                          }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                        </button>
                      )}
                    </Menu.Item>
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          className={`${
                            active ? 'text-white' : 'text-gray-500'
                          } group flex flex-row justify-between w-full items-center rounded-md px-3 py-2 text-sm`}
                        >
                          Equisafe
                          <div className='w-6 h-6 flex items-center justify-center rounded-full' style={{
                            background: 'linear-gradient(180deg, rgba(3, 0, 233, 0.64) 0%, rgba(17, 15, 74, 0.3) 100%), #ADADAD',
                          }}>{active ? <div className='w-4 h-4 rounded-full bg-white' /> : null}</div>
                        </button>
                      )}
                    </Menu.Item>
                  </div>
                </Menu.Items>
              </Transition>
            </Menu>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Bond Type</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Rating</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Assets</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Period</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Price</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Intrest</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>Maturity</div>
              <img className='ml-2' src='/filter.svg' />
            </div>
            <div className='flex-1 flex flex-row items-center'>
              <div className='text-xs font-bold'>View Bond</div>
            </div>
            <div>
              <img src='hidden-menu.svg' />
            </div>
          </div>
          <div className='flex flex-1 overflow-auto'>
            <div className='flex flex-col gap-4 flex-1 h-36 mr-3'>
              {classes?.pages?.map((page) => page.map(item => <Link href={`/exchange/${item.hash}`}>
                <div className='flex flex-row items-center flex-none gap-4 rounded-lg bg-debond/40 hover:bg-highlight-2/40 text-sm px-12 h-16'>
                  <div className='flex-1 flex flex-row items-center'>
                    <img src='' />
                    <div className='ml-2'>{item.name}</div>
                  </div>
                  <div className='flex-1'>{item.type}</div>
                  <div className='flex-1'>{item.rating}</div>
                  <div className='flex-1'>{item.assets}</div>
                  <div className='flex-1 text-xs'>{item.period}</div>
                  <div className='flex-1 text-xs flex flex-col items-center'>
                    <div>{item.assets} {item.assets}</div>
                    <div>{`(1.11 USD)`}</div>
                  </div>
                  <div className='flex-1 text-xs flex flex-col items-center'>
                    <div>5.00% ~ 10.00%</div>
                    <div>{`(APY 10% ~ 20%)`}</div>
                  </div>
                  <div className='flex-1 text-xs flex flex-col items-center'>
                    <div>DD/MM/YYYY</div>
                    <div>{`23:58:59`}</div>
                  </div>
                  <div className='flex-1'>
                    <img src='/link.svg' />
                  </div>
                  <div>
                    <div className='w-fit px-6 py-2 text-sm rounded-lg cursor-pointer self-end' style={{
                      background: 'linear-gradient(269.88deg, rgba(55, 52, 255, 0.224) 7.38%, rgba(20, 3, 163, 0.26075) 38.6%, rgba(42, 6, 45, 0.098) 96.89%), rgba(77, 14, 255, 0.35)',
                    }} onClick={() => {}}>Place A Bid</div>
                  </div>
                </div>
              </Link>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
